### ISSUE TITLE
glitchy "graphics" in unicode mode on macos (in Terminal.app with Pro color scheme)

### ISSUE THREAD

**Issue by alokdhir** [Strophox/tetrs#1]
Built it for macOS (Sonoma 14.5) and ran it. Runs well in ASCII but with no color. Some colors work in Unicode but it glitches out fairly quickly with colors bleeding all over the place.

Relevant setting -- "Declare terminal as" is set to xterm-256color. 

Tried it in iTerm2.app -- rendering much better but oddly it misses keystrokes, so it's unplayable.

Great project!

**Comment by Strophox** [comment]
Hello!

I just committed a preliminary fix (where the color is explicitly reset with characters that are 'deleted' every frame) - let me know if that fixed it! Otherwise it might be useful to attach a screenshot so I get a better idea

For controls I too added a change (tho I might have to change it back due some Windows issue)

Thank you for your feedback :)

**Comment by alokdhir** [comment]
Nice - leaking colors are fixed, though it still doesn't seem to look as intended. See attached --

<img width="789" alt="Screenshot 2024-07-28 at 12 45 06 PM" src="https://github.com/user-attachments/assets/116d87fb-71cc-445c-a6ee-68ecf53b0053">

**Comment by Strophox** [comment]
Hello - I just pushed the new version where graphics and colors are separated (and colors are now (hopefully) *efficiently* updated :)

Your screenshot presents several apparent issues
1. The block graphics characters do not fill an entire console cell.
2. Not all tetromino colors are represented.
3. For the colored tetrominos, background seems to be colored instead of the foreground/the character itself.

Number 3 is weird and I'm not sure I have any influence over that (Crossterm already provides separate coloring of the FG and BG).

For 2. I introduced a new toggle in the settings so you can turn on '16 color mode' which should color all tetrominos on all consoles :)
(although you can also play monochrome Unicode now if you wanted)

Number 1 is an issue that could be easiest fixed by your own terminal settings (different font / line height)\*, so I'd suggest that first.

(\*Although I could think of weird workarounds from my side e.g. coloring the BG instead (which yours happens to already do, but seemingly leaving the white tile in the foreground).)

Let me know how if this works for you!

**Comment by Strophox** [comment]
As far as I can tell the issues brought up here should be fixed, including 3. which can be solved with the Monochrome color palette now. I'm going to close the issue as completed.
