### ISSUE TITLE
Can't find config file

### ISSUE THREAD

**Issue by danielwerg** [Strophox/tetrs#5]
According to:

https://github.com/Strophox/tetrs/blob/08c3db69f2d93c46542c1053f7ca8d8ce257348b/tetrs_terminal/src/terminal_tetrs.rs#L192

https://github.com/Strophox/tetrs/blob/08c3db69f2d93c46542c1053f7ca8d8ce257348b/tetrs_terminal/src/terminal_tetrs.rs#L258-L263

config file should be located at `~/.config/.tetrs_terminal.json` but I couldn't find it there. `fd ".tetrs_terminal.json" ~/` also doesn't find it.

Setting do persists between session so it must be stored somewhere.

**Comment by Strophox** [comment]
Indeed, on Linux it should appear in `~/.config`, otherwise `.` (directory of program execution). Under `~/` would've been the next best option (where it's stored for e.g. [`target_os = "freebsd"`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_os)).

I haven't used `fd`.  `find ~ -name ".tetrs_terminal.json"` found it in my `~/.config` (though slow).

If you still can't find the savefile but want it removed, turn "Keep savefile" off and the program will explicitly delete it upon exit.

**Comment by danielwerg** [comment]
I figured it out. `fd` needs `-H` flag to search hidden files. Not sure why I didn't see it in `~/.config` dir I guess I wasn't looking for dot prefix?

**Comment by danielwerg** [comment]
The reason I wanted to edit config is to reset keybinds, because I didn't find a way to do so in UI.

**Comment by Strophox** [comment]
Someone else mentioned a similar reason to look for the config file manually – I'll note it down!
