### ISSUE TITLE
ARR setting seems not to have any effect

### ISSUE THREAD

**Issue by octopuserectus** [Strophox/tetrs#6]
Setting it to 0ns doesn't "teleport" pieces.

**Comment by Strophox** [comment]
Hello!

Inferring from the short description you gave (in combination with a similar you opened) it seems this is another issue stemming from common terminal limitations (see ['Important note' in README](https://github.com/Strophox/tetrs/blob/main/README.md#how-to-run) and the [similar issue mentioned](https://github.com/Strophox/tetrs/issues/7)).

*However*, this led me to discover and fix a bug in the implementation of 0 ARR for kitty terminals (where the event simulation looped infinitely.)

Thank you for your issue. :-)

**Comment by Strophox** [comment]
For future reference/readers: We implement the special actions `TeleLeft`/`TeleRight`(/`TeleRight` for 'Sonic Drop') which allow a workaround for missing Finesse due to terminal limitations.

In Terminals which support [enhanced keyboard events](<https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html>) Finesse is possible as normal
